name: cantera-latest
channels:
  - cantera
  - cantera/label/dev
dependencies:
  - cantera
  - matplotlib
  - pandas
  - seaborn
  - scipy
  - pyyaml
  - more-itertools
  - glob3
                         
